version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
    - POSTGRES_USER=main
    - POSTGRES_PASSWORD=620631
    - POSTGRES_DB=bonussystem
    ports:
    - '5432:5432'
    volumes:
    - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local
